docs/README.md, docs/hyperparameter-selection.md, neuralprophet/configure.py, neuralprophet/forecaster.py, tests/debug.py, tests/test_unit.py
If not defined, both batch_size and epochs are automatically set based on the dataset size. 
They are set in a manner that controls the total number training steps to be around 1000 to 4000.
also new:
train_speed (int, float) a quick setting to speed up or slow down model fitting [-3, -2, -1, 0, 1, 2, 3]
potentially useful when under-, over-fitting, or simply in a hurry.
applies epochs *= 2**-train_speed, batch_size *= 2**train_speed, learning_rate *= 2**train_speed,
default None: equivalent to 0.
=> Automatic batch_size and epochs setting, train_speed option

README.md
Dev Install section is missing quotes around ".[dev]".
Tested on macOS.
=> Update Dev Install command for README.md

neuralprophet/forecaster.py
Unfortunately, sphinx (or furo?) gets upset when you leave out a newline before `Args:` in the docstrings.
Because of this, some entries in the documentation looked like this:
To fix this, I have added newlines in front of all docstring `Args:` that were missing them. For consistency among all functions, I also added newlines before every `Returns:` (this is just a style choice and black does not care either).
I checked if this fixes the problem and it does:
I also corrected the formatting of parameter types in the `add_seasonality` function:
Please note that I have so far only checked and fixed the `forecaster.py` file. There may be more such mistakes/inconsistencies in other files.
There is also one big issue remaining in the `forecaster.py` file: the params of the `NeuralProphet` class …
=> fix documentation parameter formatting

docs/source/conf.py, neuralprophet/forecaster.py
As mentioned in my last PR #561, the parameters of the `NeuralProphet` class were not visible in the documentation. I moved them up to the docstring directly under the class definition to make them visible.
In the docstring, some of the parameters had comments as headers, grouping them together, like the following one:
```
n_lags (int): Previous time series steps to include in auto-regression. Aka AR-order
ar_sparsity (float): [0-1], how much sparsity to enduce in the AR-coefficients.
Should be around (# nonzero components) / (AR order), eg. 3/100 = 0.03
```
This double number sign is not recognized by sphinx as a comment, resulting in those lines being interpreted as parameters themselves. 
Unfortunately, sphinx (or rather: [reStructuredText](https://www.sphinx-doc.org/en/master/usage/res …
=> make class params visible and introduce sphinx comment command

requirements.txt
dataclasses is included in python 3.7+, so is not needed (or desired) there.
=> update requirement for dataclasses package

neuralprophet/df_utils.py
Fix #692.
The problem in #692 arises because, for each series, the code tries to obtain the first datestamp using `df['ds'][0]`. However, when there is a data frame in a long format (with ID), potentially not all series share the same index (not all start at `0`). Therefore, it is best to use `df['ds'].iloc[0]`.
=> [FIX] `infer_frequency` for monthly, yearly and quarterly data

neuralprophet/forecaster.py
Hi @ourownstory @karl-richter ,
When using the global_modeling tutorial I realised that when forecasting multiple time series, the output of the `predict` method gives some NaNs IDs (see picture attached).
I had a look and the problem might come from #656 and, in particular, from the method `_reshape_raw_predictions_to_forecst_df`. At the end of this method we have:
`df_forecast = pd.concat([df_forecast, pd.Series(yhat, name=comp)], axis=1, ignore_index=False)`
the problem is that the index in `df_forecast` and `pd.Series(yhat, name=comp)` do match if only 1 time series is passed or in the first time series passed when passing multiple. However the `df_forecast` of the second time series passed, has an indexation that wont match the `pd.Series`.
I think resetting the index at the start of …
=> FIX: NaN IDs output in the predict method for Multiple Time Series

.editorconfig
All `yml` files in the project have an indention of 2 spaces. `Makefile` and `bat` files requires indention to be tabs. Editorconfig now preserves this choice.
=> Editorconfig: Fix indention for Makefile, yml and bat files

neuralprophet/forecaster.py, neuralprophet/plot_forecast_plotly.py, tests/test_plotting.py, tests/test_unit.py
Added support for the plotting of uncertainty quantiles to plotly.
Tested with the feature-use tutorial notebooks created by @Kevin-Chen0. 
Added plotting test for the plotly uncertainty plotting functionality.
Building on the ideas by #368, but created a new PR due to incompatible changes.
=> Plotly quantile support

tests/test_regularization.py, tests/utils/dataset_generators.py
A collection of test cases to check regularization functions. Contains some unit tests for base functions and several integration tests to ensure higher regularization values results in lower weights (high regularization -> weights close to zero).
Pull request to add tests for issue #133
=> Write test cases for events and holidays regularization

neuralprophet/df_utils.py
In #684, users addressed that the `np.quantile` function is incompatible with any Python version lower than 3.8.
This is due to a change in the Numpy api introduced with version 1.22.0, however, this version is not compatible with any older Python version.
In the [Numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html), the developers state that they renamed the `method` function argument (previously: `interpolation`) and added argument options. Since the option we are using (`method="higher"`) has previously been available, the simple solution I propose is to wrap the statement with a conditional that switches between the old and the new function call based on the installed Numpy version. The `np.quantile` is only called two times in the same function within the …
=> [bugfix] Addressed np.quantile issue

neuralprophet/forecaster.py
Removed some left over debug print statement. In case we want to keep it, better move it to logging.
=> remove print statement from forecaster.py

pyproject.toml, setup.cfg
Adjust `isort` and `flake8` configs to work with `black`.
=> Tooling config black

neuralprophet/df_utils.py, neuralprophet/forecaster.py, neuralprophet/time_dataset.py, tests/test_integration.py, tests/test_unit.py, tests/test_utils.py
**Same changes as in PR #747, but with develop as base branch.**
*added df_utils.drop_missing_from_df() dropping data from df in accordance with drop_nan_after_init() in TimeDataset
*while loop for as long as there are remaining NaN windows after imputation
*find all indices containing NaN in df
*drop NaNs window and lagged values before
*Changed max_lags to n_lags in __handle_missing_data()
*When predicting (only) and dropping nan, only drop values related to lags, not n_forecasts
*Added new helper function: inner join of input df and forecast df to ensure dropped and imputed data points are neglected for model evaluation
*Added kwarg "predict_steps" needed for proper data drop
*predict_steps either is n_forecasts or periods (case of fcst into unknown future)
*predict_steps indicates …
=> [bug-fix] Enable predictions into unknown and known future in case of remaining NaN windows after imputation

neuralprophet/forecaster.py, neuralprophet/plot_forecast.py, neuralprophet/utils.py, tests/test_uncertainty.py
Same changes as in PR #764, but now with develop as the base branch
*output df of utils.fcst_df_to_last_forecast() now contains quantile columns if quantiles are specified in the model
*quantile columns are generated in the same way as the yhat columns
*Added fig1 = plot_... to every plot function in test_uncertainty.py
=> [Feature] enable quantiles for get_latest_forecast() output df

neuralprophet/df_utils.py, neuralprophet/forecaster.py, neuralprophet/time_dataset.py
Corrects all docstrings in `forecaster.py`, `df_utils.py`, and `time_dataset.py` to talk about ID, not df_dict (completely deprecate dicts)
closes #806 
Next step: Update the code base to remove support for dicts of df as input, see #810
=> Corrected all docstrings regarding df dictionaries

neuralprophet/forecaster.py
refer to issue #429 
makes PR #551 unnecessary
**Problem**
Multiplicative components are not output correctly in the forecast df due to being computed incorrectly. 
**Solution**
The multiplicative components are not re-scaled properly. Therefore, the re-scaling of all multiplicative components is added in predict_raw().
=> [bugfix] fix re-scaling of multiplicative components in forecast df

.gitignore, docs/source/Live_plot_during_training.nblink, docs/source/benchmarking.nblink, docs/source/network_architecture_visualization.nblink, docs/source/plotly.nblink, docs/source/uncertainty_estimation_peyton_manning.nblink, requirements-docs.txt
- Define all required packages for building the documentation as `requirements-docs.txt`
- Fix all links to notebooks in docs (remove missing, add new ones)
- Add docs generated output to gitignore
=> Define documentation build requirements and fix documentation notebook links

tests/test_regularization.py
To fix the failed test cases on the regularization lagged regressor test case by releasing the boundaries of the test case values. Weirdly about 99% of the times the case case runs it results in boundaries of `0.01` and `0.99`, yet 1% might fall far off. Running the case case for 200 times, yielded those extreme values: `highest low 0.3371017` and `lowest high 0.64243484`, therefore those new test case boundaries.
=> relax constraints for regularization lagged regressor test case

neuralprophet/forecaster.py, neuralprophet/plot_forecast.py, neuralprophet/plot_forecast_plotly.py
Closes #807 
`plot_components()` threw an Error whenever a global modal has been fitted with local normalization
The desired ID of the global df shall now be passed as an argument, e.g. `plot_components(forecast, df_name='df1')`.
If `df_name` is not specified (i.e. no df with multiple IDs), the default name `__df__` is used.
=> Allow component plot with locally-normalized global df

neuralprophet/configure.py, neuralprophet/forecaster.py, requirements.txt
Two problems are fixed with this PR:
- Fix for #868: OrderedDict does behave differently as typing across python version apparently, super weird (see other [issues](https://github.com/python/mypy/issues/6904))
- Fixes missing `typing.Literal` issue with python version 3.7
=> 868 bug runtime exception during collection when declaring configlaggedregressors

.github/workflows/metrics.yml
If a new pr is opened from a branch on a fork, the metrics job seems to search for the metrics on the main branch of the respective fork. As this is not intended, the repository to load the artifacts from is now specified.
=> [bugfix] Added repository to metrics artifact download

.github/workflows/ci.yml
Close #895 
- The errors withing the docstring (autodoc) module are only propagated as warnings, therefore we let sphnix-build fail on any warning
=> 895 test documentation build and make any warnings fail the test

neuralprophet/utils.py
The rich progress bar seemed to cause significant overhead in the training loop, pushing the training time to 5.2 minutes for 89 epochs on peyton manning data. Training time before Lightning was ~2.5 min.
When deactivating all logging in Lightning, the training time could be pushed to 55 seconds. [Reference](https://towardsdatascience.com/pytorch-lightning-vs-deepspeed-vs-fsdp-vs-ffcv-vs-e0d6b2a95719)
When adding all checkpointing functionality back and switching to the default tqdm progress bar, the training takes 1.32 minutes (which @Kevin-Chen0 and I find acceptable).
This pr removes the custom progress bar.
=> [lightning] remove rich progress bar

tests/test_integration.py
This will prevent the macOS and Windows build PR tests from getting hung.
=> Commented out test_progress_display in test_integration.py.

neuralprophet/forecaster.py, tests/test_integration.py
Added plot parameter in the NeuralProphet fit method that can toggle whether `plt.show()` is executed or not. Therefore, this param can be set to `False` for unit testing. This will prevent `test_progress_display` from hanging the PR tests, as seen Issue [#928](https://github.com/ourownstory/neural_prophet/issues/928).
=> Added plot param of the NeuralProphet fit() and uncomment test_progress_display in test_integration.py.

neuralprophet/forecaster.py, neuralprophet/utils.py
Added the minimal mode to the Lightning Trainer (speedup up to 2.5x).
Speedup the training when using the progress bar up to 2x.
=> [lightning] refactored Trainer args

neuralprophet/forecaster.py, tests/test_integration.py
I found a more elegant way on how we can avoide the pytest with .show to fail.
It seems like the cause of the issue is that the python session on the gh action workers is non-interactive, which causes the `.show()` call to crash the session. This can be avoided by calling `.isinteractive()` on the matplotlib session.
Let me know what you think.
References:
- https://stackoverflow.com/questions/29620884/how-to-put-python-3-4-matplotlib-in-non-interactive-mode
- https://gist.github.com/matthewfeickert/84245837f09673b2e7afea929c016904
=> refactored test failure

.github/workflows/metrics.yml, tests/test_model_performance.py
Added training time to the benchmarks + only hide the figures, but not the metrics.
=> Time in model training benchmark

tests/test_configure.py
Basic tests for training config quantiles initialization.
Motivation: if we refactor the handling of configuration options and their internals it is good to have some test cases to ensure we do not break anything. This is a starting point for more work in this direction and to provide the template for other test cases people can replicate if they work on some of the configuration objects and want some safety net :)
=> [tests] Add tests for configure

neuralprophet/configure.py, neuralprophet/forecaster.py
Resolve type annotation issues in configure file and ignore epochs `None` type warning due to almost impossible to fix with `dataclasses` - see [[source]](https://stackoverflow.com/questions/56839030/dataclasses-how-to-ignore-none-values-using-asdict)
=> [typing] Resolve type annotation issues in configure file

neuralprophet/configure.py, neuralprophet/df_utils.py, neuralprophet/time_dataset.py, neuralprophet/utils.py
=> [typing] Add ConfigEvents type annotations

neuralprophet/time_net.py
As pointed out in #1002, some tensors have remained on the CPU when training with a GPU. This has previously been adressed #1010, it seems like some tensors remained on the wrong device.
- Moved all tensors to the correct device (checked all usages of `torch.zeros`, `torch.ones`, `torch.tensor` via strg+F)
- Added the usage of `self. meta_used_in_model` in the forward function
=> Follow-up tensors on wrong device

tests/test_integration.py, tests/test_uncertainty.py, tutorials/feature-use/autoregression_yosemite_temps.ipynb, tutorials/feature-use/uncertainty_estimation.ipynb
Thanks @gozdii for the hint in https://github.com/ourownstory/neural_prophet/discussions/890
=> [fix] Replace all deprecated plot_last_forecast with plot_latest_forecast

tests/test_model_performance.py
- The training time across pull requests is often off by a lot although the code did not change significantly
- Measure the performance of the CPU by performing pi calculation operations. Use the metrics to normalize the training time across different system requirements.
=> Normalize training speed metric

tests/test_model_performance.py
- The system performance metrics are calculated once before the beginning of all tests
- The metrics are now calculated before each training starts to account for more accurate metrics.
=> Improved system performance tracker

.github/workflows/codeql-analysis.yml
- There are a lot of Github CI jobs running for each commit and it starts to get slow
- Nobody seems to be really using CodeQL - or does anyone?
- Run CodeQL Github CI action only on main branch
=> [devops] Cleanup and limit CodeQL Github action to main branch

neuralprophet/time_dataset.py
- The dataloader currently uses a for loop in the `__getitem__` function to retrieve a sample from the dataset. Since for a dataset with 10.000 samples that is trained for 100 epochs, this function is called 1 Mio. times, pre-computing the samples should bring a speed-up of the model training.
- Pre-compute the samples to only use indexing during retrieval.
=> Refactored dataloader

tests/metrics/compareMetrics.py
- The training time metric depends on the system performance, but github action workers have varying system specifications.
- This pr normalizes the training time based on the currently available system specs.
=> Normalize training time metric

neuralprophet/forecaster.py
- When plotting the loss of the training using `progress="plot"`, an error is raised.
- This PR fixes this by removing the .show() aftter the figure. We figured out that matplotlib calls .show() internally, so the figure is till shown in notebooks.
=> [Fix] Fixed error in plot loss

requirements/base.txt
Numpy 1.24.0 seems to cause problem with the matplotlib plotting engine. Thus, we restrict numpy to <1.24.0 for the time being.
Restrict numpy to <1.24.0
=> Restict numpy version to <1.24.0

neuralprophet/forecaster.py
Make calibration dataset and alpha mandatory when the conformal predict function is being called
- Removed the default setting for calibration_df and alpha under theconformal_predict function
- Updated the comment for parameter as well
=> remove default settings (None for calibration df and 0.1 for alpha)

neuralprophet/utils.py
Fixes #1093 
`plot_latest_forecast()` throws an Error because with conformal prediction, a new column name `yhat1 +qhat` is inserted in the `forecast` dataframe, which we have not dealt with before. 
Ignore those new column names for now
=> [Bug-fix] Enable test_plot_conformal_prediction with auto-regression on plot_latest_forecast

neuralprophet/time_dataset.py
Fixes #1099
Adding country holidays with m.add_country_holidays() triggers an index error when the input df contains multiple time series (i.e. when glocal/global modeling is used).
Resetting the index of the incoming time series in TimeDataset.make_events_features() resolves the problem.
=> [Bug-fix] Enable holidays when using global/glocal modeling

neuralprophet/forecaster.py, neuralprophet/time_net.py
Fixes #1053 
This code portion produced a warning on every single training step, which leads to huge, unnecessary log output. 
```
if not self.config_normalization.global_normalization:
log.warning("When Global modeling with local normalization, metrics are displayed in normalized scale.")
else:
...
```
Moved the warning to `m.fit()`
=> [Bug-fix] Refactor warning about global normalization to forecaster.py

requirements/base.txt
- The Lightning version requirement is very strict
- Loosened the requirement for Lightning
- Loosened the requirement for torchmetrics
- Remove the rich dependency (no longer used)
=> Lightning version

neuralprophet/components/README.md, neuralprophet/components/router.py, neuralprophet/components/seasonality/__init__.py, neuralprophet/components/seasonality/fourier.py, neuralprophet/components/seasonality/seasonality.py, neuralprophet/forecaster.py, neuralprophet/hdays.py, neuralprophet/plot_forecast_plotly.py, neuralprophet/plot_model_parameters_plotly.py, neuralprophet/plot_utils.py, neuralprophet/time_net.py, tests/test_integration.py, tests/test_unit.py
- Following the example of trend, the seasonality component is modularized.
- Created a new Seasonality abstract and FourierSeasonality class.
- Find the new class diagram [here](https://github.com/ourownstory/neural_prophet/tree/feature/modular_seasonality/neuralprophet/components).
=> Seasonality modularization

neuralprophet/df_utils.py, requirements/base.txt
Fixes #1130 
Currently, NeuralProphet does not allow a future regressor to only contain unique values. When global modeling, however, there are reasonable cases in which some IDs may have only unique values, while others don't. 
Instead of throwing an Error immediately, we first check whether we have unique values cross all IDs. If not, we give a warning.
=> Allow unique values for future regressor of one time series in global modeling

neuralprophet/forecaster.py
- Former PR #1116 caused a pyright error in github actions
- Fixed by defining a list that is empty per default, and not empty for certain conditions
=> Fixed pyright error raised from unbound list

docs/source/guides/hyperparameter-selection.md, neuralprophet/configure.py
In the guide hyperparemeter-selection, it says 
'`n_changepoints` is the number of changepoints selected along the series for the trend. The default value for this is 5.' 
But the correct value would be 10, being consistent with the code.
Changed the value of 5 to 10 in the guide
=> [fix] default value of n_changepoints given correctly in the docs

neuralprophet/utils.py
- The default learning rate finder by lightning does not smooth the loss results, thus the results yielded are unstable.
- A first implementation of the loss smoothing has been implemented with the introduction of lightning.
- This PR improves the smoother implementation and applies a more conservative learning rate selection function.
=> [minor] Refactored Learning Rate Finder

.github/workflows/linters.yml, neuralprophet/df_utils.py
- We support both python version, but we get new errors in python `3.10` which do not exist in `3.7` (`3.7` is most important for colab and other use cases, so focus on that)
- Change python version to `3.7` from `3.10` for pyright
=> [devops] Downgrade python to 3.7 for pyright

neuralprophet/configure.py, neuralprophet/df_utils.py, neuralprophet/forecaster.py, neuralprophet/utils.py
=> [typing] Add typing for user facing functions

neuralprophet/time_net.py
Bug because `self.season_params` does not exist anymore with the newly modularized seasonality. 
Change to `self.seasonality.season_params`
=> [minor] Adjust seasonality reg to modularized code

tests/test_uncertainty.py, tutorials/feature-use/uncertainty_conformal_prediction.ipynb
- Allows conformal evaluation for double-digit (and beyond) multistep forecasting.
- Change the way how n_forecasts is extracted.
=> [refactor] Modified n_forecasts in  _infer_evaluate_params_from_dataset() method in conformal.py

neuralprophet/uncertainty.py, tutorials/feature-use/uncertainty_conformal_prediction.ipynb
- Added QR so its uncertainty metrics `interval_width` can also be compared to the conformal prediction (CP) metrics.
- Included QR into the `uncertainty_evaluate()` method in uncertainty.py.
=> [refactor] Add quantile regression (QR) as an uncertainty evalution metric in uncertainty.py

requirements/base.txt, requirements/dev.txt
- With the release of pytorch 2.0 our package is broken (for python > 3.7)
- One great example for #911 
- Limit version of `pytorch` to `<2.0`
- Limit version of `pytorch-lightning` to `<2.0.0`
- Limit version of `dash` to `<2.9` (dependency of plotly)
`pip install git+https://github.com/ourownstory/neural_prophet.git@fix-broken-pytorch`
=> [fix] Limit broken dependency versions (mainly pytorch < 2.0)

CONTRIBUTING.md
Labels in contributing.md were outdated, fixes #1241 
Added "in development" label
=> [docs] outdated labels in contributing.md

tests/test_uncertainty.py
- Plotting is not part of the scope for test_uncertainty.py.
- Removed code relating to `PLOT` in test_uncertainty.py
=> [refactor] Removed plotting in test_uncertainty.py.

neuralprophet/uncertainty.py
=> [refactor] Changed int() to round() for q_hat_idx in uncertainty.py.

neuralprophet/df_utils.py
=> [fix] Calculate major frequency percentage properly

neuralprophet/components/trend/static.py
Fixes #1168 
The StaticTrend() class (called when growth='off) in static.py does not follow the forecasting pattern of all the other components.
Example: PiecewiseLinear() (when growth not off) forecasts for every sample, and ends up with a shape of (batch_size, n_forecasts, quantiles). Static trend is in shape (batch_size, 1, quantiles). Although the static trend is constant, we need it to be in the same shape as the other components.
Repeat static trend component `n_forecasts` times instead of only once to avoid dimension errors
=> [minor] Repeat static trend component n_forecasts times instead of only once

neuralprophet/data/process.py, neuralprophet/df_utils.py, tests/test_integration.py, tests/test_regularization.py, tests/test_unit.py
Fixes #1227 
Closes #1250 
In the case of only having unique values for future (or lagged) regressors, we currently remove the regressor column from the data. However, the `config_regressor` still survives (although being empty), which causes an error. 
In the event of all future (or lagged) regressors are removed due to only having single values in the column, the fitting and predicting procedure runs through without considering any regressors (i.e. the model is trained as if no regressors would have been specified).
=> [fix] Remove regressor config if all regressors are removed due to unique values 

neuralprophet/data/process.py
Some warnings could be fixed, fixes https://github.com/ourownstory/neural_prophet/issues/1159
**Fixed warnings**
**Not addressed and reason**
warnings.warn("Could not import lttbc; will use a (slower) python alternative.") 
--> will be removed in the near future, see https://github.com/predict-idlab/plotly-resampler/issues/180
--> is already fixed in torch 2.0, see here for the commit, that fixes it: https://github.com/pytorch/pytorch/pull/95545 (merged on Feb 27)
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
__import__("pkg_resources").declare_namespace(__name__)
--> Lightning knows about the warning and are on it, see …
=> [minor] Address warnings

neuralprophet/data/split.py, neuralprophet/forecaster.py
- Encapsulate `_get_maybe_extend_periods` and `_maybe_extend_df`
=> [minor] lighten forecaster step 2 - encapsulate _get_maybe_extend_periods and _maybe_extend_df

neuralprophet/data/process.py, neuralprophet/data/split.py, neuralprophet/forecaster.py
- Encapsulate `_make_future_dataframe ` 
- Encapsulate  `_check_dataframe`. Note: `model` still needs to be passed, since config is set within function …
=> [refactor] Encapsulate _make_future_dataframe and _check_dataframe

neuralprophet/data/process.py, neuralprophet/forecaster.py, tests/test_integration.py
- Encapsulate `_validate_column_name` including docstring and typing
=> [refactor] Encapsulate _validate_column_name

neuralprophet/data/transform.py, neuralprophet/forecaster.py, tests/test_unit.py
- Encapsulate `_normalize` including docstring and typing
=> [refactor] Encapsulate _normalize

neuralprophet/data/process.py, neuralprophet/forecaster.py, tests/test_integration.py, tests/test_unit.py
- Encapsulate `_handle_missing_data ` including docstring and typing
- Rename and encapsulate `_handle_missing_data_single_id` including docstring and typing
Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTIN …
=> [refactor] Encapsulate _handle_missing_data and _handle_missing_data_single_id

neuralprophet/data/process.py, neuralprophet/forecaster.py
- Encapsulate `_prepare_dataframe_to_predict` including docstring and typing. Model still needs to for passing on to `_check_dataframe`
=> [refactor] Encapsulate _prepare_dataframe_to_predict

neuralprophet/utils.py
- We would like to add docstring examples for functions that are unclear to call individually to users.
- add example for `set_random_seed()`
- add example for `set_log_level()`
- N.a. [ ] I have added pytests to check whether my feature / fix works.
=> [minor] add docstring examples

neuralprophet/data/process.py, neuralprophet/forecaster.py, neuralprophet/np_types.py
- Encapsulate `_convert_raw_predictions_to_raw_df` including docstring and typing.
=> [refactor] Encapsulate _convert_raw_predictions_to_raw_df

neuralprophet/data/process.py, neuralprophet/forecaster.py, neuralprophet/np_types.py
close #1133
- Encapsulate `_reshape_raw_predictions_to_forecst_df` including docstring and typing. 
- Add new `Component `type
=> [refactor] Encapsulate _reshape_raw_predictions_to_forecst_df

neuralprophet/data/process.py, tests/test_integration.py
- Fixes #1294 
- Closes #1257 
When using auto-regression with a dataset that is smaller than `n_forecasts` + `n_lags` the fit method throws an IndexError. This hides the real problem, which is that the user is trying to train a model on not enough data. 
- raise an error which tells the user to lower the number of forecasts and/or lags, or asks for a larger dataset
=> [fix] Raise ValueError when df contains not enough rows

.github/workflows/ci.yml
- There has not been any difference between the operating systems so far
- Remove macos and windows, as linux runs fastest
- Fixed #991
=> [devops] Remove macos and windows from Github actions

.github/workflows/linters.yml, pyproject.toml
- Ruff is a new super fast linting tool (could replace flake8 and isort) https://github.com/charliermarsh/ruff
=> [devops] Add ruff github action

neuralprophet/time_net.py
see #1348 
changed `= +` to `+=`
=> [minor] fix sum of components 

neuralprophet/time_net.py
=> fixed assert error

neuralprophet/data/process.py, neuralprophet/df_utils.py
This part of a bigger change, where successively NP will be sped up.
Split_df gets very slow, the more IDs are added
The following sub functions are accelerated:
No. IDs | Before total | After Total | Before check_datafram | After check_dataframe | Before handle_missing_data | After handle_missing_data | Before split_df | After split_df
-- | -- | -- | -- | -- | -- | -- | -- | --
8 | 1.4 | 0.5 | 0.3 | 0.2 | 0.19 | 0.03 | 0.2 | 0.1
16 | 3.8 | 0.9 | 0.5 | 0.4 | 0.52 | 0.06 | 0.3 | 0.2
32 | 21.6 | 2.2 | 1.3 | 0.7 | 0.91 | 0.11 | 0.8 | 0.5
64 | 48.5 | 5.2 | 4.4 | 1.8 | 5.4 | 0.42 | 3.7 | 1.5
128 | 131.9 | 9 | 12 | 3.4 | 18 | 0.85 | 12 | 4.4
256 | 570.9 | 16 | 35 | 6.7 | 55 | 1.33 | 37 | 4.5
512 | 1504.1 | 35 | 161 | 14 | 151 | 1.18 | 97 | 6.4
=> [major] Speed up split_df by vectorizing for loops

neuralprophet/df_utils.py, neuralprophet/utils_torch.py
Flake8 and pyright warnings in #1390
=> [bug] Fix pyright and flake8 warnings

poetry.lock
Update poetry dependencies to latest versions
=> Update poetry dependencies

neuralprophet/data/process.py, neuralprophet/df_utils.py, neuralprophet/forecaster.py, neuralprophet/time_dataset.py, tests/test_unit.py
The whole computation was done with float64 types, but torch tensors are float32 anyway and most of the ML models use float32 values. This will affect model accuracy but I think its worth it because we safe a lot of memory!
- y and yhat values: float32 if float32 is inserted, float64 if float64 is inserted
- time values: will always be float64 because `np.datetime64`
- feature values (events): float32
=> [minor] Memory efficient float32 types instead of float64 types

neuralprophet/df_utils.py, neuralprophet/plot_utils.py
ruf warnings because type instead of isinstance was used
=> [bug] fixed ruff warnings

neuralprophet/forecaster.py
resolves #1367 
Add a `verbose` arg to `NeuralProphet.test`, surfacing the verbose option on `trainer.test`
=> [minor] Add a verbose option to NeuralProphet.test

neuralprophet/plot_utils.py
- closes #1391 
- Removed the wrong warning in case of global model.
=> [fix] Remove wrong plotting warning

neuralprophet/utils.py
After `save`, `forecaster.predict` won't work as the trainer is removed. 
To reproduce:
```python 
import pandas as pd
from neuralprophet import NeuralProphet, set_log_level, df_utils
from neuralprophet import save as npsave
data_location = "https://raw.githubusercontent.com/ourownstory/neuralprophet-data/main/datasets/yosemite_temps.csv"
df = pd.read_csv(data_location)
m = NeuralProphet()
_ = m.fit(df, epochs=2, learning_rate=0.01, progress=None)
npsave(m, "test.np")
forecast = m.predict(df.iloc[-2:])
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[110], line 12
10 _ = m.fit(df, …
```
=> Add the trainer back to the forecaster after saving model to file

.github/workflows/ci.yml
due to plotting backend unreliably installing in CI jobs.
=> Skip windows python 3.8 tests in ci.yml

tests/test_plotting.py
- During testing some plots opened.
- Built-in plotting in conformal_predict disabled when running pytests.
=> [fix] Pytests Plots

.github/workflows/metrics.yml, poetry.lock, pyproject.toml, tests/test_model_performance.py
- Update to include new test from #1455
- may clash with #1113
- Unsuccessfully tried to update CI to use poetry instead of pip
=> [Devops] update metrics ci with new tests 

docs/source/how-to-guides/feature-guides/hyperparameter-selection.md, docs/zh/超参数选取.md, neuralprophet/configure.py, neuralprophet/forecaster.py, tests/test_configure.py, tests/test_uncertainty.py
- Editing all files to mention SmoothL1Loss correctly instead of Huber loss.
- Remains backwards compatible.
- make beta of 1.0 explicit
=> [Minor] SmoothL1Loss correctly mentioned instead of Huber

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md, docs/source/how-to-guides/feature-guides/hyperparameter-selection.md
=> docs: fix typos

README.md
for the better documentation.
added full_stops for sentences.
added full_stops in the end of sentences in readme.
=> added full_stops

neuralprophet/utils.py, tests/test_utils.py
- On CPU-only machines, loading gives: 
torch.load RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
- Adjusted the load function to pass map_location to torch.load
=> [minor] Torch Load

neuralprophet/df_utils.py
- typo
- prefered -> preferred
=> [docs] fix typo in df_utils.py

neuralprophet/plot_model_parameters_plotly.py
- When plotting the yearly seasonality component with model.plot_parameters(), the year is shown on the xaxis.
- Solves #1500 
- Only occurs using plotly 
- Issue does not occur with daily or weekly seasonalities
- Adjusted x-axis tick labels in plot_yearly
=> [fix] Plot_parameter - Yearly Seasonality

docs/source/how-to-guides/feature-guides/MLflow_and_NeuralProphet.ipynb
=> [docs] Fix MLFlow Sphinx test error

neuralprophet/forecaster.py
-  closes #1580 
- closes #1575
- Change the order of init of trainer and trend
=> [fix] fix bug #1580

neuralprophet/utils.py, tests/test_utils.py
-  closes #1553 
- Added File Like support similar to torch
=> [minor] Support io.bytes output

neuralprophet/configure.py
=> [Minor] Raise Error if ar_reg is set an dn_lags is null

neuralprophet/df_utils.py
=> [Minor] Fix frequency inference if NaT

neuralprophet/configure.py, neuralprophet/forecaster.py, neuralprophet/hdays_utils.py, neuralprophet/time_dataset.py, neuralprophet/utils.py, tests/test_hdays_utils.py, tests/test_utils.py, tests/utils/dataset_generators.py
=> [minor] add subdivisions to holidays

tests/test_future_regressor_nn.py, tests/test_regularization.py
Speedup new tests by using offline dataset
=> [Devops] speed up future-reg-nn tests

tests/test_event_utils.py
=> [Minor] Remove failing test from testing pipeline

neuralprophet/utils.py
- pytorch lightning 2 ProgressBarBase class renamed to ProgressBar
=> pytorch lightning 2 ProgressBar class rename

neuralprophet/components/future_regressors/neural_nets.py, neuralprophet/components/future_regressors/shared_neural_nets.py, neuralprophet/components/future_regressors/shared_neural_nets_coef.py, neuralprophet/configure.py, neuralprophet/forecaster.py, tests/test_future_regressor_nn.py
- fixes issue #1375 
Removed the arguments `future_regressors_num_hidden_layers` and `future_regressors_d_hidden` and replaced them with a single argument `future_regressors_layers : Optional[List[int]]`. (following the practice of `ar_layers`)
- length holds the number of hidden layers
- values hold the dimension of each layer
=> [Major] Combined future regressor layer arguments into one single integer list `regressors_layers` like `ar_layers`

.github/workflows/metrics.yml
Addressing [Warning](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
=> Update CI metrics.yml to use Node 20 

neuralprophet/forecaster.py, neuralprophet/time_dataset.py, neuralprophet/time_net.py, neuralprophet/utils_time_dataset.py
In preparation of true component modularization, the ComponentStacker is further abstracted with regards to component stacking and unstacking functions.
=> [Minor] Componentstacker dataclass and abstraction of stacking and unstacking of components

neuralprophet/data/process.py, neuralprophet/data/split.py, neuralprophet/data/transform.py, neuralprophet/df_utils.py, neuralprophet/forecaster.py, tests/test_unit.py
Remove all copies of DataFrame except for top-level function call (when user passes df), and few necessary exceptions.
Background: Due to various pieces of code contributed by different contributors, unnecessary copies of the DataFrame were made out of precaution. This is here being addressed.
=> [Minor] Reduce DataFrame copies
