- neuralprophet/neural_prophet.py
- neuralprophet/test_debug.py
update name of forecast_in_focus to highlight_forecast_step_n
> update name of forecast_in_focus to highlight_forecast_step_n

- neuralprophet/df_utils.py
- tests/debug.py
- tests/test_unit.py
Conflicts resolved, test case updated
> Sobyah fix issue 53

- tutorials/feature-use/autoregression_yosemite_temps.ipynb
Change 'icreasing' to 'increasing'
> fix typo in autoregression_yosemite_temps.ipynb tutorial

- neuralprophet/forecaster.py
torch.pi is wrong when torch version is 1.9.0
> change torch.pi to np.pi

- neuralprophet/forecaster.py
@ourownstory please add description of ``n_historic_predictions`` variable
> add documentation for make_future_dataframe

- neuralprophet/df_utils.py
- neuralprophet/forecaster.py
- tests/test_integration.py
- tests/test_unit.py
Now cross-validation can also be applied for dict of time series
> Cross validation for dict

- requirements.txt
* torch < 1.7.0 has no torch.maximum
* torch 1.7.0 and 1.7.1 have issue with ParameterDict
> Require torch 1.8.0

- neuralprophet/forecaster.py
- tests/test_integration.py
- tutorials/feature-use/collect_predictions.ipynb
Create clean branch for get_latest_forecast based on #677 PR
> Create clean branch for get_latest_forecast based on #677 PR

- neuralprophet/forecaster.py
- tests/test_integration.py
Add npsave/npload function and its corresponding test cases.
> Add npsave/npload function

- .editorconfig
"EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems." - https://editorconfig.org/
> Add editorconfig to project

- neuralprophet/forecaster.py
*Fixed assertion – Now `assert len(fcst["ID"].unique()) > 1` instead of `assert fcst["ID"].unique() > 1` in thise plot functions that raise Exceptions.
*Re-formatted Docstring of `get_latest_forecast()` according to numpy styleguide
> Fixed Exceptions & Docstring in plot functions

- neuralprophet/forecaster.py
- tests/test_unit.py
> add hint to add_country_holidays that previous value will be overridden

- neuralprophet/forecaster.py
add example of how to specify list of metrics
> improve metrics documentation

- neuralprophet/configure.py
- neuralprophet/df_utils.py
- neuralprophet/forecaster.py
- neuralprophet/plot_forecast.py
- neuralprophet/plot_forecast_plotly.py
- neuralprophet/plot_model_parameters.py
- neuralprophet/plot_model_parameters_plotly.py
- neuralprophet/time_dataset.py
- neuralprophet/time_net.py
- neuralprophet/utils.py
- tests/test_integration.py
- tests/test_regularization.py
- tests/test_unit.py
Close #72
Consider `_config` to `config_` rename of internal attributes for release notes.
> Rename all configurations to start with 'config_'

- neuralprophet/plot_model_parameters.py
Fix for #750, all tensors are of shape [1] and not multi dimensional. Tried with quantities and growth and without, all four options. Had to manually circumvent the `m.config_trend.n_changepoints` in line 356 because I did not get a combination of parameters for `growth=on` and `n_changepoints=0`.
> 750 fix plot growth off issue

- neuralprophet/forecaster.py
change changepoints_range from 0.9 to 0.8
> [enhancement] increase stability of last trend segment

- neuralprophet/forecaster.py
This PR is to just make things more clear when the library outputs an error saying "insufficient data".
> [enhancement] Improve insufficient data error messages

- neuralprophet/df_utils.py
improve error message
to help with #809
> add error message to valuerror

- neuralprophet/configure.py
- Sort and remove imports
- Fix typings
> Cleanup configure.py imports and typings

- .github/workflows/website.yml
- .gitignore
- _site/html/index.html
- docs/index.html
- docs/source/_templates/index.html
- docs/source/conf.py
- docs/source/uncertainty_estimation.nblink
- docs/source/uncertainty_estimation_peyton_manning.nblink
- neuralprophet/df_utils.py
> 843 automatic deployment of docs with GitHub action

- .github/workflows/website.yml
Also includes the fixes for the broken github website action.
> Create branch for website and only deploy from that

- .github/workflows/linters.yml
> 844 Enable black jupyter integration for github actions

- CONTRIBUTING.md
> 846 add note on typing to contributingmd

- .github/workflows/ci.yml
> add matrix for python versions 3.7 and 3.10 in tests

- neuralprophet/configure.py
- neuralprophet/forecaster.py
- neuralprophet/utils.py
**Status quo**
The learning rate finder is a) unstable and strongly dependent on the lr finder range + seed b) the suggestion by the lr finder often does not match the lr a visual inspection would suggest but is strongly influenced by the gradient of local minima.
> [lightning] Learning rate finder optimization

- neuralprophet/TorchProphet.py
- neuralprophet/__init__.py
- neuralprophet/forecaster.py
- neuralprophet/plot_forecast.py
- neuralprophet/plot_forecast_plotly.py
- neuralprophet/plot_model_parameters.py
- neuralprophet/plot_model_parameters_plotly.py
- neuralprophet/time_dataset.py
- neuralprophet/time_net.py
- setup.cfg
Cherry picking commits from #833
> Flake8 fixes

- .github/workflows/linters.yml
Replacement for #833 containing the original flake8 and isort github actions
> 825 GitHub actions for isort and flake8 linters

- .github/workflows/ci.yml
- .github/workflows/website.yml
@ourownstory thanks for finding my mistake, should have been part of the other PR already, my bad
> fix docs requirements path and filename

- neuralprophet/configure.py
- neuralprophet/df_utils.py
- neuralprophet/forecaster.py
- neuralprophet/time_dataset.py
- neuralprophet/time_net.py
- neuralprophet/utils.py
- tests/test_unit.py
> 778 update docstrings to match typing of variables

- neuralprophet/df_utils.py
> [bugfix] Fix index mismatch adding events when global df with multiple IDs is used

- neuralprophet/forecaster.py
> [bug] Forecast output dataframe contains all float dtypes instead of having some objects

- codecov.yml
See [documentation](https://docs.codecov.com/docs/commit-status)
> [devops] Code coverage threshold fix

- neuralprophet/forecaster.py
- neuralprophet/time_net.py
- neuralprophet/utils.py
- tests/test_glocal.py
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19BDjs1ZxbwoklGG376ECwnM81iONRxvA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=HcN2Wmd)
https://github.com/ourownstory/neural_prophet/issues/969
> Unified the naming of variables - num and nb

- scripts/setup.sh
Simple script to help people quickly setup their basic development environment.
> [devops] Add shell script to setup basic development environment

- neuralprophet/df_utils.py
- neuralprophet/forecaster.py
- tests/test_plotting.py
Signed-off-by: Mostafa Dahab <mostafa@dahab.io>
- Fix a small issue with string Interpolation
- Fix a small issue with string Interpolation
> Fix string Interpolation

- CONTRIBUTING.md
- Labels were outdated in contributing guidelines
- Update labels
> Fix label links in contributing guidelines

- neuralprophet/_version.py
Merge back the latest version number from our release branch
> bump version number to 0.5.0rc2

- neuralprophet/configure.py
- neuralprophet/forecaster.py
- neuralprophet/plot_forecast_matplotlib.py
- neuralprophet/plot_forecast_plotly.py
- neuralprophet/plot_model_parameters_matplotlib.py
- neuralprophet/plot_model_parameters_plotly.py
- neuralprophet/plot_utils.py
- neuralprophet/time_dataset.py
- neuralprophet/time_net.py
- neuralprophet/utils.py
- tests/test_glocal.py
- tests/test_integration.py
> [refactor] Rename config_seasonality and add typings

- neuralprophet/configure.py
- neuralprophet/forecaster.py
- neuralprophet/time_net.py
Remove the `config_train.reg_lambda_season` as it is only a duplicate of `config_season.reg_lambda`
> [refactor] Remove duplicate season reg lambda

- neuralprophet/df_utils.py
- Code in `create_dict_for_events_or_regressors` is heavily nested and returns same dict in the end
- Unfolded the logic and returned final result directly, resulting is way less nested code
- Should improve readability
> [refactor] create dict for events or regressors

- neuralprophet/utils.py
> black edited utils.py

- neuralprophet/time_net.py
- Typing violation in TimeNet
- Fixed the typing, pyright violation
> [devops] Fixed pyright violation of seasonalities

- neuralprophet/time_net.py
> [refactor] incorporate typing for time_net.py

- neuralprophet/df_utils.py
Nothing changed, just more flat control flow and hopefully easier to read. Now also with typing :)
> [refactor] Refactor the prep_or_copy_df method

- neuralprophet/forecaster.py
- `df_prep_or_copy` got called twice next to another, now it is only called once
> [refactor] Remove duplicate df_prep_or_copy call

- neuralprophet/__init__.py
- neuralprophet/conformal.py
- neuralprophet/forecaster.py
- neuralprophet/uncertainty.py
- tests/test_uncertainty.py
- tutorials/feature-use/uncertainty_conformal_prediction.ipynb
> [Refactor] Renamed conformal.py to uncertainty.py and conformal_evalute() to uncertainty_evaluate().

- neuralprophet/df_utils.py
- tests/test_integration.py
Reverts ourownstory/neural_prophet#1256
> Revert "[minor] Allow lagged regressors with only unique values for global modeling"

- docs/source/guides/changes-from-prophet.md
> [docs] add note on flexible multiplicativity from prophet

- .github/workflows/website.yml
- Fix the broken deployment of the website
> [website] Fix website deployment

- docs/source/new-tutorials/next-steps.md
add content to next steps in tutorials #767
> [docs] Add next steps to tutorials

- neuralprophet/utils.py
> [fix] Raise Exception again to avoid UnboundLocalError

- poetry.lock
- Update the poetry lock file to use latest package versions
> [minor] Update dependencies to latest versions

- .github/workflows/website.yml
> [website] Fix the deployment of the website with poetry

- README.md
- Link outdated in readme
- updated link in docs
> fix tutorials link in readme

- neuralprophet/time_net.py
see #1348 
call `compute_components` with `corrected_input`
This PR is only for release 0.6.0.
It cannot be merged on the current main as the code changed since then
> [minor] fix sum of components in 0.6.0

- docs/source/how-to-guides/feature-guides/Live_plot_during_training.ipynb
- docs/source/how-to-guides/feature-guides/collect_predictions.ipynb
- docs/source/how-to-guides/feature-guides/conditional_seasonality_peyton.ipynb
- docs/source/how-to-guides/feature-guides/season_multiplicative_air_travel.ipynb
- docs/source/how-to-guides/feature-guides/sparse_autoregression_yosemite_temps.ipynb
- docs/source/how-to-guides/feature-guides/test_and_crossvalidate.ipynb
- docs/source/how-to-guides/feature-guides/uncertainty_quantification.ipynb
- Tutorials (Feature guides and application examples) crash during training when using Colab. Solves Issue #1399
- It seems like an issue with the pre-installed packages from Colab. Training worked after uninstalling some of the pre-installed packages. 
To avoid future conflicts, it would be nicer to uninstall all pre-installed packages. Sadly, I did not find such a feature for Colab,
> [fix] Tutorials on Colab Crash

- pyproject.toml
> [devops] bump version-number to 1.0.0rc5

- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
- make `tests.dependencies` part of `dev.dependencies`
- `group.pyright` optional
> group dev dependencies and update lock

- .github/workflows/metrics.yml
- tests/metrics/debug-energy-price-daily.ipynb
- tests/test_model_performance.py
remove dual horizon tests for simplicity and introduce one new test on energy price data as seen in tutorials.
> [tests] add new test and remove 3 duplicate tests

- README.md
Fixed #1471
Added contributors section to the readme.md
@ourownstory  review it and merged the PR!
> [Docs] Added contributors section to  README.md

- docs/source/how-to-guides/feature-guides/MLflow_and_NeuralProphet.ipynb
- Tutorial for integration of MLflow and NeuralProphet
- Solves https://github.com/ourownstory/neural_prophet/issues/1483
- Following #1487
> [docs] MLflow tutorial

- .gitignore
- poetry.lock
- pyproject.toml
Expand python versions to 3.11
> [devops] Support python 3.11

- neuralprophet/__main__.py
- poetry.lock
- pyproject.toml
- scripts/pre_push.bash
> [Devops] Poetry Dev dependencies update

- pyproject.toml
Prepare intermediate release before 1.0.0
> [Devops] bump version 0.7.0

- poetry.lock
- pyproject.toml
- scripts/pre_push.bash
- tests/pytest.ini
mostly upgraded dev dependencies, but also upgraded torchmetrics to 1.0.0 among few smaller upgrades.
> [Devops] Upgrade dependencies to more recent range of dependencies

- neuralprophet/forecaster.py
- missing 's' in parameter 'include_previous_forecasts'
> [doc] get_latest_forecast

- poetry.lock
Update Poetry lock to newest state of compatible packages.
> [DevOps] update poetry

- neuralprophet/time_dataset.py
- poetry.lock
- tests/utils/benchmark_time_dataset.py
- Speedup the TimeDataset class 
> [Minor] Torchify TimeDataset
